# Generated by Django 2.2.1 on 2019-08-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reg_no', models.CharField(max_length=20)),
                ('group', models.CharField(max_length=20)),
                ('programme', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static_local/media')),
                ('fee_balance', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
