# Generated by Django 2.2.1 on 2019-08-24 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20190824_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='disp',
        ),
    ]
