# Generated by Django 2.2.1 on 2019-08-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_student_deferred'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='duration',
            field=models.IntegerField(default=4),
        ),
    ]
