# Generated by Django 2.2.1 on 2019-08-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_programme_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='year_sem',
            field=models.CharField(choices=[('1', 'Year I Semester I'), ('2', 'Year I Semester II'), ('3', 'Year II Semester I'), ('4', 'Year II Semester II'), ('5', 'Year III Semester I'), ('6', 'Year III Semester II'), ('7', 'Year IV Semester I'), ('8', 'Year IV Semester II'), ('9', 'Year V Semester I'), ('10', 'Year V Semester II'), ('11', 'Year VI Semester I'), ('12', 'Year VI Semester II')], default='8', max_length=1),
        ),
    ]
