# Generated by Django 2.2.1 on 2019-08-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_group_year_sem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('units', models.IntegerField(default=3)),
            ],
        ),
        migrations.AddField(
            model_name='programme',
            name='units',
            field=models.ManyToManyField(blank=True, to='students.Courses'),
        ),
    ]
