# Generated by Django 2.2.1 on 2019-08-30 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_auto_20190830_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='units',
        ),
    ]
