# Generated by Django 2.2.1 on 2019-08-30 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_remove_programme_units'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
