# Generated by Django 2.2.1 on 2019-09-07 09:20

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_auto_20190830_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=students.models.upload_image_path),
        ),
    ]
