# Generated by Django 2.2.1 on 2019-08-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='t_type',
            field=models.CharField(choices=[('D', 'Debit'), ('C', 'Credit')], default='C', max_length=10),
            preserve_default=False,
        ),
    ]
