# Generated by Django 2.2.1 on 2019-08-24 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_transaction_t_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 8, 24, 11, 40, 51, 196759)),
            preserve_default=False,
        ),
    ]
